apiVersion: v1
kind: Service
metadata: 
  name: k8sproject
  labels:
    app: k8sproject
spec:
  selector:
    matchLabels: 
      app: k8sproject
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 31200
